# Langauge Similariy : Analysing Results

In [78]:
import pandas as pd
import numpy as np
import seaborn as sns
from statistics import mean, variance

1) Read in results:

In [79]:
lan_results_raw = pd.read_csv('LanSimilarity_results_.csv', sep=',')
lan_results_raw.head()

,DIST,LAN_1,LAN_2,f1_1,f1_2,f1_3,f1_4,f1_avg,eval_loss_1,eval_loss_2,...,prec_1,prec_2,prec_3,prec_4,prec_avg,rec_1,rec_2,rec_3,rec_4,rec_avg
0,0.0,Fr,Fr,0.893213,0.888047,0.876112,0.887097,0.886117,0.198437,0.202131,...,0.886195,0.878942,0.870113,0.882885,0.879534,0.900342,0.897344,0.882195,0.891349,0.892807
1,0.0,Cz,Cz,0.906074,0.910235,0.915396,0.906259,0.909491,0.128661,0.115112,...,0.901365,0.903469,0.910765,0.896681,0.903070,0.910832,0.917103,0.920074,0.916044,0.916013
2,0.0,Hng,Hng,0.904727,0.912152,0.915793,0.914913,0.911896,0.100900,0.097007,...,0.898685,0.909110,0.909587,0.905993,0.905844,0.910852,0.915215,0.922083,0.924011,0.918040
3,0.0,Swd,Swd,0.969269,0.968846,0.970608,0.971073,0.969949,0.027116,0.030358,...,0.968793,0.964743,0.967114,0.967158,0.966952,0.969745,0.972984,0.974128,0.975020,0.972969
4,0.0,Swd,Nor,0.775514,0.793024,0.773457,0.778720,0.780179,0.427731,0.409371,...,0.763254,0.780430,0.767143,0.769053,0.769970,0.788174,0.806031,0.779876,0.788632,0.790678

2) Data Cleaning: Filter for f1 scores + mean/variance calculation of f1 score

In [80]:
three_it = lan_results_raw[lan_results_raw['f1_4'] == 0]
three_it.head()

,DIST,LAN_1,LAN_2,f1_1,f1_2,f1_3,f1_4,f1_avg,eval_loss_1,eval_loss_2,...,prec_1,prec_2,prec_3,prec_4,prec_avg,rec_1,rec_2,rec_3,rec_4,rec_avg
51,1.0,Grg,Est,0.771919,0.769370,0.746793,0.0,0.572020,0.283787,0.295506,...,0.768837,0.755030,0.745950,0.0,0.567454,0.775026,0.784266,0.747637,0.0,0.576732
52,1.0,Ltv,Pol,0.770045,0.769416,0.745273,0.0,0.571183,0.369154,0.388595,...,0.746563,0.748436,0.723985,0.0,0.554746,0.795052,0.791606,0.767850,0.0,0.588627
56,1.0,Ukr,Lit,0.759872,0.771770,0.778513,0.0,0.577539,0.310880,0.295128,...,0.737877,0.745699,0.758511,0.0,0.560522,0.783220,0.799730,0.799599,0.0,0.595637
57,1.0,Ukr,Ltv,0.661722,0.660862,0.660491,0.0,0.495769,0.651767,0.692945,...,0.620064,0.621282,0.626225,0.0,0.466893,0.709380,0.705829,0.698724,0.0,0.528483
58,1.0,Sln,Blg,0.817473,0.816999,0.814546,0.0,0.612255,0.337765,0.369435,...,0.799497,0.797140,0.791211,0.0,0.596962,0.836275,0.837873,0.839300,0.0,0.628362

In [110]:
lan_results_f1 = lan_results_raw[['DIST','LAN_1', 'LAN_2', 'f1_1','f1_2','f1_3','f1_4']]
    
lan_results_f1 = lan_results_f1.reindex(columns = ['DIST','LAN_1', 'LAN_2','f1_1','f1_2','f1_3','f1_4','mean','variance', 'standard dev'])

lan_results_f1['f1_1'] = lan_results_f1['f1_1'].apply(lambda x: x*100)
lan_results_f1['f1_2'] = lan_results_f1['f1_2'].apply(lambda x: x*100)
lan_results_f1['f1_3'] = lan_results_f1['f1_3'].apply(lambda x: x*100)
lan_results_f1['f1_4'] = lan_results_f1['f1_4'].apply(lambda x: x*100)

for index, row in lan_results_f1.iterrows():
    
    if row['f1_4'] == 0:
        lan_results_f1.at[index,'mean'] = np.mean([row['f1_1'],row['f1_2'],row['f1_3']])
        lan_results_f1.at[index,'variance'] = np.var([row['f1_1'],row['f1_2'],row['f1_3']])
        lan_results_f1.at[index,'standard dev'] = np.std([row['f1_1'],row['f1_2'],row['f1_3']])
    else:
        lan_results_f1.at[index,'mean'] = np.mean([row['f1_1'],row['f1_2'],row['f1_3'],row['f1_4']])
        lan_results_f1.at[index,'variance'] = np.var([row['f1_1'],row['f1_2'],row['f1_3'],row['f1_4']])
        lan_results_f1.at[index,'standard dev'] = np.std([row['f1_1'],row['f1_2'],row['f1_3'],row['f1_4']])

lan_results_f1.head()

,DIST,LAN_1,LAN_2,f1_1,f1_2,f1_3,f1_4,mean,variance,standard dev
0,0.0,Fr,Fr,89.321267,88.804723,87.611210,88.709677,88.611719,0.387831,0.622761
1,0.0,Cz,Cz,90.607395,91.023465,91.539557,90.625936,90.949088,0.143842,0.379265
2,0.0,Hng,Hng,90.472742,91.215227,91.579269,91.491346,91.189646,0.189359,0.435154
3,0.0,Swd,Swd,96.926853,96.884581,97.060834,97.107316,96.994896,0.008446,0.091904
4,0.0,Swd,Nor,77.551420,79.302396,77.345679,77.871967,78.017865,0.585177,0.764969

3) Analysing monolingual results - mean/ variance

In [111]:
monolingual = lan_results_f1[(lan_results_f1['DIST'] == 0.0) & (lan_results_f1['LAN_1'] == lan_results_f1['LAN_2'])]
len(monolingual)

31

In [112]:
monolingual

,DIST,LAN_1,LAN_2,f1_1,f1_2,f1_3,f1_4,mean,variance,standard dev
0,0.0,Fr,Fr,89.321267,88.804723,87.611210,88.709677,88.611719,0.387831,0.622761
1,0.0,Cz,Cz,90.607395,91.023465,91.539557,90.625936,90.949088,0.143842,0.379265
2,0.0,Hng,Hng,90.472742,91.215227,91.579269,91.491346,91.189646,0.189359,0.435154
3,0.0,Swd,Swd,96.926853,96.884581,97.060834,97.107316,96.994896,0.008446,0.091904
6,0.0,Nor,Nor,92.202652,92.710129,91.823511,92.107069,92.210840,0.102537,0.320214
7,0.0,Rus,Rus,90.099751,90.253338,90.613144,89.854709,90.205236,0.075675,0.275090
8,0.0,Rom,Rom,92.513234,92.581525,94.074356,93.165330,93.083611,0.391418,0.625634
9,0.0,Alb,Alb,95.773867,94.778895,95.065789,95.696693,95.328811,0.176250,0.419821
10,0.0,It,It,91.976433,90.644316,92.139324,90.717300,91.369343,0.478063,0.691421
14,0.0,Prt,Prt,89.624777,90.149537,88.943489,90.231153,89.737239,0.264157,0.513962
18,0.0,Spn,Spn,89.730253,89.588087,89.670965,90.067502,89.764202,0.033213,0.182245
19,0.0,Grk,Grk,88.870608,88.980847,88.456124,87.688472,88.499013,0.257266,0.507214
20,0.0,Lit,Lit,90.820073,91.147174,89.442098,90.443103,90.463112,0.409558,0.639967
21,0.0,SCr,SCr,94.674556,94.390146,94.649007,94.043467,94.439294,0.064606,0.254176
24,0.0,Trk,Trk,90.279330,90.730643,90.694598,89.327549,90.258030,0.320051,0.565730
25,0.0,Arm,Arm,91.080418,92.640919,92.101496,91.793471,91.904076,0.318139,0.564038
28,0.0,Est,Est,91.539163,91.754277,90.471950,90.828341,91.148433,0.269951,0.519568
29,0.0,Wel,Wel,92.688543,92.329117,92.496311,92.718113,92.558021,0.024718,0.157219
30,0.0,Grg,Grg,85.638180,85.758006,85.659998,85.028726,85.521227,0.082889,0.287905
31,0.0,Fin,Fin,89.950446,89.335646,89.506110,90.113877,89.726520,0.100388,0.316840
32,0.0,Brt,Brt,92.017478,92.872855,93.014585,92.299396,92.551079,0.166613,0.408182
33,0.0,Eng,Eng,80.283778,81.021424,80.791867,81.172806,80.817469,0.113336,0.336654
34,0.0,Bsq,Bsq,93.637634,94.297583,94.937900,93.938523,94.202910,0.234653,0.484410
38,0.0,Sln,Sln,92.821173,93.201230,93.573204,92.772230,93.091959,0.104772,0.323685
42,0.0,Pol,Pol,90.307915,89.800167,90.612970,90.329605,90.262664,0.085787,0.292894
43,0.0,Blg,Blg,92.776311,93.492139,92.679544,92.717516,92.916378,0.111689,0.334199
44,0.0,Ukr,Ukr,91.738005,92.029986,92.280036,92.470541,92.129642,0.075535,0.274837
45,0.0,Dut,Dut,90.205744,90.279094,91.269587,90.847085,90.650378,0.189416,0.435220
46,0.0,Ltv,Ltv,92.162102,91.559242,91.673204,91.496330,91.722720,0.068371,0.261479
47,0.0,Tat,Tat,98.224398,98.540856,98.046689,98.273856,98.271450,0.031329,0.177001
48,0.0,Grm,Grm,86.312434,85.518672,86.538054,87.272727,86.410472,0.391170,0.625436

4) Analysing results per distance

In [117]:
average_results = {}

for dist in lan_results_f1['DIST'].unique():
    df_temp = lan_results_f1[lan_results_f1['DIST'] == dist]
    mean = np.mean(df_temp['mean'].values)
    std = np.mean(df_temp['standard dev'].values)
    
    
    average_results[dist] = [mean, std]

average_results

{0.0: [85.53876452666344, 0.9282200347270491],
 1.0: [69.1053690049619, 2.039119958638802]}

In [114]:
lan_results_f1[lan_results_f1['DIST']==1.0].sort_values(by='variance', ascending=False).head()

,DIST,LAN_1,LAN_2,f1_1,f1_2,f1_3,f1_4,mean,variance,standard dev
71,1.0,Cz,SCr,47.057466,48.596594,55.806795,24.281150,43.935501,139.673398,11.818350
60,1.0,Sln,SCr,45.080587,22.554003,24.324324,24.001668,28.990146,86.745259,9.313713
65,1.0,Pol,SCr,37.862259,50.081833,58.992285,38.948680,46.471264,75.129105,8.667705
85,1.0,Trk,Tat,71.201049,64.985563,52.788825,0.000000,62.991813,58.489186,7.647822
49,1.0,Wel,Tat,68.053492,60.898408,57.075600,70.586213,64.153428,29.320507,5.414841

In [115]:
lan_results_f1[lan_results_f1['DIST']==0.0].sort_values(by='variance', ascending=False).head()

,DIST,LAN_1,LAN_2,f1_1,f1_2,f1_3,f1_4,mean,variance,standard dev
23,0.0,Blg,SCr,39.410681,58.584374,60.083008,67.518341,56.399101,107.647619,10.375337
27,0.0,Est,Arm,44.069741,47.445516,36.619136,46.423118,43.639378,17.926225,4.233937
5,0.0,Nor,Swd,74.200234,82.109504,81.314408,77.809743,78.858472,9.849960,3.138465
40,0.0,Pol,Ukr,65.062000,68.231366,63.933576,62.293794,64.880184,4.712239,2.170769
35,0.0,Ukr,Sln,79.935610,83.472567,81.615599,79.264485,81.072065,2.654179,1.629165

In [ ]:
#Findings:

# - stable monolingual results over the four iterations - not expected
    #?high diversity in authors across the splits

# - but some high variance in the f1-score for the different language pair