# Langauge Similariy : Analysing Results of mBERT

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from matplotlib.ticker import FormatStrFormatter
import seaborn as sns
from statistics import mean, variance
%matplotlib inline

1) Read in results:

In [3]:
lan_results_raw = pd.read_csv('CoNLL_results.csv', sep=',')
lan_results_raw.head()

,LAN_1,LAN_2,f1_1,f1_2,f1_3,f1_4,f1_avg,eval_loss_1,eval_loss_2,eval_loss_3,...,prec_1,prec_2,prec_3,prec_4,prec_avg,rec_1,rec_2,rec_3,rec_4,rec_avg
0,Eng,Dut,0.813822,0.827479,0.803153,0.812622,0.814269,0.253949,0.245530,0.275856,...,0.790319,0.808300,0.775020,0.791246,0.791221,0.838765,0.847591,0.833405,0.835184,0.838736
1,Dut,Eng,0.716452,0.723121,0.707584,0.707259,0.713604,0.502277,0.472887,0.512018,...,0.691971,0.696964,0.675745,0.675302,0.684995,0.742729,0.751318,0.742572,0.742391,0.744753
2,Eng,Spn,0.635020,0.679665,0.665047,0.669805,0.662384,0.660834,0.563054,0.675317,...,0.603513,0.645253,0.637472,0.636066,0.630576,0.669998,0.717955,0.695116,0.707323,0.697598
3,Spn,Eng,0.694286,0.702629,0.698135,0.706028,0.700269,0.566224,0.504933,0.516033,...,0.663934,0.671471,0.665161,0.672170,0.668184,0.727545,0.736819,0.734548,0.743478,0.735597
4,Dut,Spn,0.852545,0.855558,0.836406,0.857380,0.850472,0.322096,0.291284,0.339750,...,0.834344,0.833908,0.813199,0.838785,0.830059,0.871557,0.878362,0.860977,0.876819,0.871929

In [5]:
lan_results_f1 = lan_results_raw[['LAN_1', 'LAN_2', 'f1_1','f1_2','f1_3','f1_4']]
    
lan_results_f1 = lan_results_f1.reindex(columns = ['LAN_1', 'LAN_2','f1_1','f1_2','f1_3','f1_4','mean','variance', 'standard dev'])

lan_results_f1['f1_1'] = lan_results_f1['f1_1'].apply(lambda x: x*100)
lan_results_f1['f1_2'] = lan_results_f1['f1_2'].apply(lambda x: x*100)
lan_results_f1['f1_3'] = lan_results_f1['f1_3'].apply(lambda x: x*100)
lan_results_f1['f1_4'] = lan_results_f1['f1_4'].apply(lambda x: x*100)

for index, row in lan_results_f1.iterrows():
    
    if row['f1_4'] == 0:
        lan_results_f1.at[index,'mean'] = np.mean([row['f1_1'],row['f1_2'],row['f1_3']])
        lan_results_f1.at[index,'variance'] = np.var([row['f1_1'],row['f1_2'],row['f1_3']])
        lan_results_f1.at[index,'standard dev'] = np.std([row['f1_1'],row['f1_2'],row['f1_3']])
    else:
        lan_results_f1.at[index,'mean'] = np.mean([row['f1_1'],row['f1_2'],row['f1_3'],row['f1_4']])
        lan_results_f1.at[index,'variance'] = np.var([row['f1_1'],row['f1_2'],row['f1_3'],row['f1_4']])
        lan_results_f1.at[index,'standard dev'] = np.std([row['f1_1'],row['f1_2'],row['f1_3'],row['f1_4']])

lan_results_f1

,LAN_1,LAN_2,f1_1,f1_2,f1_3,f1_4,mean,variance,standard dev
0,Eng,Dut,81.382199,82.747902,80.315287,81.262157,81.426886,0.752467,0.867448
1,Dut,Eng,71.645178,72.312084,70.758421,70.725898,71.360395,0.437943,0.661772
2,Eng,Spn,63.501964,67.966510,66.504742,66.980482,66.238424,2.774018,1.665538
3,Spn,Eng,69.428571,70.262910,69.813460,70.602808,70.026937,0.197731,0.444670
4,Dut,Spn,85.254500,85.555818,83.640634,85.737996,85.047237,0.689323,0.830255
5,Spn,Dut,83.523759,84.721641,81.594768,82.730924,83.142773,1.300978,1.140604